# Generated by Django 4.2 on 2023-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('add', models.DateField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
