# Generated by Django 4.2 on 2023-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_info_addjob_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='requirements',
            field=models.TextField(default='', max_length=400),
        ),
    ]
