# Generated by Django 4.2 on 2023-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_addjob_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='cat',
        ),
        migrations.AddField(
            model_name='apply',
            name='obtained_marks',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='total_marks',
            field=models.IntegerField(default=True),
        ),
    ]
