# Generated by Django 4.2 on 2023-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_apply_cat_apply_obtained_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='address',
            field=models.CharField(default=True, max_length=70),
        ),
    ]
