# Generated by Django 4.2 on 2023-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_apply_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='resume',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
