# Generated by Django 4.2 on 2023-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_remove_apply_id_remove_apply_resume_remove_info_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply',
            field=models.CharField(default=True, max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
