# Generated by Django 4.2 on 2023-05-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_apply_apply_alter_apply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
