# Generated by Django 4.2 on 2023-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
