# Generated by Django 4.2 on 2023-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_alter_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='enroll/'),
        ),
    ]
