# Generated by Django 4.2 on 2023-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_alter_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='enroll/'),
        ),
    ]
